# Use an official Node.js image as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the React app for production
RUN npm run build

# Use an official Nginx image to serve the build
FROM nginx:stable-alpine

# Copy the build output to the Nginx web server directory
COPY --from=0 /app/build /usr/share/nginx/html

# Expose the port on which Nginx will serve the app
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
