version: "3.8"

services:
  users_service:
    build:
      context: ./sharents_dev/users_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./sharents_dev/users_service:/app
    ports:
      - "8001:8001"
    environment:
      - ATLAS_URI=mongodb+srv://sharents_name:sharents_password@sharents.kf7lh.mongodb.net/users_db?retryWrites=true&w=majority&appName=Sharents

  children_service:
    build:
      context: ./sharents_dev/children_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./sharents_dev/children_service:/app
    ports:
      - "8002:8002"
    environment:
      - ATLAS_URI=mongodb+srv://sharents_name:sharents_password@sharents.kf7lh.mongodb.net/children_db?retryWrites=true&w=majority&appName=Sharents

  events_service:
    build:
      context: ./sharents_dev/events_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./sharents_dev/events_service:/app
    ports:
      - "8003:8003"
    environment:
      - ATLAS_URI=mongodb+srv://sharents_name:sharents_password@sharents.kf7lh.mongodb.net/events_db?retryWrites=true&w=majority&appName=Sharents

  milestones_media_service:
    build:
      context: ./sharents_dev/milestones_media_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./sharents_dev/milestones_media_service:/app
    ports:
      - "8004:8004"
    environment:
      - ATLAS_URI=mongodb+srv://sharents_name:sharents_password@sharents.kf7lh.mongodb.net/milestones_media_db?retryWrites=true&w=majority&appName=Sharents

  frontend_service:
    build:
      context: ./frontend_app
      dockerfile: Dockerfile.dev  # Specify Dockerfile here if it's not named 'Dockerfile'
    ports:
      - "3000:80" # Map port 3000 on host to port 80 in the container where Nginx serves the app
    depends_on:
      - users_service
      - children_service
      - events_service
      - milestones_media_service
