version: "3.8"

services:
  children_service:
    build:
      context: ./sharents_dev/children_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./sharents_dev/children_service:/app
    ports:
      - "8002:8002"
    environment:
      - MONGODB_URI=mongodb+srv://sharents_name:sharents_password@sharents.kf7lh.mongodb.net/children_db?retryWrites=true&w=majority&appName=Sharents

  events_service:
    build:
      context: ./sharents_dev/events_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./sharents_dev/events_service:/app
    ports:
      - "8003:8003"
    environment:
      - MONGODB_URI=mongodb+srv://sharents_name:sharents_password@sharents.kf7lh.mongodb.net/events_db?retryWrites=true&w=majority&appName=Sharents

  milestones_media_service:
    build:
      context: ./sharents_dev/milestones_media_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./sharents_dev/milestones_media_service:/app
    ports:
      - "8004:8004"
    environment:
      - MONGODB_URI=mongodb+srv://sharents_name:sharents_password@sharents.kf7lh.mongodb.net/milestones_media_db?retryWrites=true&w=majority&appName=Sharents

  users_service:
    build:
      context: ./sharents_dev/users_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./sharents_dev/users_service:/app
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URI=mongodb+srv://sharents_name:sharents_password@sharents.kf7lh.mongodb.net/users_db?retryWrites=true&w=majority&appName=Sharents
